name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test Node ${{ matrix.node-version }} / Grunt ${{ matrix.grunt-version }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16.x, 18.x, 20.x, 22.x]
        grunt-version: ['^1.4.0', '^1.5.3', '^1.6.1']
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install specific Grunt version
      run: npm install grunt@${{ matrix.grunt-version }} --save-dev
      
    - name: Verify Grunt version
      run: npx grunt --version
      
    - name: Run linting
      run: npm run lint || echo "Lint script not found, skipping..."
      
    - name: Run tests
      run: npm test
